// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ApiAuth
 */
export type ApiAuth = {
    /**
     * Type
     */
    type: 'api_key';
    /**
     * Header
     */
    header?: string;
};

/**
 * ApiDefinitionAdmin
 */
export type ApiDefinitionAdmin = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Category
     */
    category: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Auth Type
     */
    auth_type: string;
    /**
     * Parameters
     */
    parameters: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Response Schema
     */
    response_schema: {
        [key: string]: unknown;
    };
    /**
     * Error Codes
     */
    error_codes: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Examples
     */
    examples: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Visibility
     */
    visibility: string;
    /**
     * Status
     */
    status: string;
    /**
     * Is Free
     */
    is_free: boolean;
    /**
     * Source
     */
    source: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Provider Ref
     */
    provider_ref?: string | null;
    /**
     * Cache Rules
     */
    cache_rules: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * ApiDefinitionCreate
 */
export type ApiDefinitionCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary?: string;
    /**
     * Category
     */
    category: string;
    /**
     * Method
     */
    method?: string;
    /**
     * Path
     */
    path: string;
    /**
     * Auth Type
     */
    auth_type?: 'api_key';
    /**
     * Parameters
     */
    parameters?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Response Schema
     */
    response_schema?: {
        [key: string]: unknown;
    };
    /**
     * Error Codes
     */
    error_codes?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Examples
     */
    examples?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Visibility
     */
    visibility?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Is Free
     */
    is_free?: boolean;
    /**
     * Source
     */
    source?: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Provider Ref
     */
    provider_ref?: string | null;
    /**
     * Cache Rules
     */
    cache_rules?: {
        [key: string]: unknown;
    };
};

/**
 * ApiDefinitionUpdate
 */
export type ApiDefinitionUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Method
     */
    method?: string | null;
    /**
     * Path
     */
    path?: string | null;
    /**
     * Auth Type
     */
    auth_type?: 'api_key' | null;
    /**
     * Parameters
     */
    parameters?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Response Schema
     */
    response_schema?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error Codes
     */
    error_codes?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Examples
     */
    examples?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Visibility
     */
    visibility?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Is Free
     */
    is_free?: boolean | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Adapter Name
     */
    adapter_name?: string | null;
    /**
     * Provider Ref
     */
    provider_ref?: string | null;
    /**
     * Cache Rules
     */
    cache_rules?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ApiDetail
 */
export type ApiDetail = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Category
     */
    category: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    auth: ApiAuth;
    /**
     * Is Free
     */
    is_free: boolean;
    /**
     * Status
     */
    status: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Parameters
     */
    parameters: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Response Schema
     */
    response_schema: {
        [key: string]: unknown;
    };
    /**
     * Errors
     */
    errors: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Examples
     */
    examples: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Source
     */
    source: string;
    /**
     * Cache Rules
     */
    cache_rules: {
        [key: string]: unknown;
    };
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CatalogItem
 */
export type CatalogItem = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Category
     */
    category: string;
    /**
     * Method
     */
    method: string;
    /**
     * Path
     */
    path: string;
    /**
     * Auth Type
     */
    auth_type: string;
    /**
     * Is Free
     */
    is_free: boolean;
    /**
     * Status
     */
    status: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * CatalogPage
 */
export type CatalogPage = {
    /**
     * Data
     */
    data: Array<CatalogItem>;
    /**
     * Count
     */
    count: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * EmailAddressRequest
 */
export type EmailAddressRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * GitHubLinkRequest
 */
export type GitHubLinkRequest = {
    /**
     * Current Password
     */
    current_password: string;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRequestPasswordResetData = {
    body: EmailAddressRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/request-password-reset';
};

export type loginRequestPasswordResetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRequestPasswordResetError = loginRequestPasswordResetErrors[keyof loginRequestPasswordResetErrors];

export type loginRequestPasswordResetResponses = {
    /**
     * Successful Response
     */
    202: Message;
};

export type loginRequestPasswordResetResponse = loginRequestPasswordResetResponses[keyof loginRequestPasswordResetResponses];

export type loginRequestEmailVerificationData = {
    body: EmailAddressRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/request-email-verification';
};

export type loginRequestEmailVerificationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRequestEmailVerificationError = loginRequestEmailVerificationErrors[keyof loginRequestEmailVerificationErrors];

export type loginRequestEmailVerificationResponses = {
    /**
     * Successful Response
     */
    202: Message;
};

export type loginRequestEmailVerificationResponse = loginRequestEmailVerificationResponses[keyof loginRequestEmailVerificationResponses];

export type loginLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type loginLogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginLogoutResponse = loginLogoutResponses[keyof loginLogoutResponses];

export type loginVerifyEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/v1/auth/verify-email';
};

export type loginVerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginVerifyEmailError = loginVerifyEmailErrors[keyof loginVerifyEmailErrors];

export type loginVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginVerifyEmailResponse = loginVerifyEmailResponses[keyof loginVerifyEmailResponses];

export type loginGithubLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/github';
};

export type loginGithubCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/github/callback';
};

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersRequestMyEmailVerificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/email-verification';
};

export type usersRequestMyEmailVerificationResponses = {
    /**
     * Successful Response
     */
    202: Message;
};

export type usersRequestMyEmailVerificationResponse = usersRequestMyEmailVerificationResponses[keyof usersRequestMyEmailVerificationResponses];

export type usersStartGithubLinkData = {
    body: GitHubLinkRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/github/link';
};

export type usersStartGithubLinkErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersStartGithubLinkError = usersStartGithubLinkErrors[keyof usersStartGithubLinkErrors];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type catalogSearchCatalogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Query
         */
        query?: string | null;
        /**
         * Category
         */
        category?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/v1/catalog';
};

export type catalogSearchCatalogErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type catalogSearchCatalogError = catalogSearchCatalogErrors[keyof catalogSearchCatalogErrors];

export type catalogSearchCatalogResponses = {
    /**
     * Successful Response
     */
    200: CatalogPage;
};

export type catalogSearchCatalogResponse = catalogSearchCatalogResponses[keyof catalogSearchCatalogResponses];

export type catalogGetCatalogDetailData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/catalog/{slug}';
};

export type catalogGetCatalogDetailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type catalogGetCatalogDetailError = catalogGetCatalogDetailErrors[keyof catalogGetCatalogDetailErrors];

export type catalogGetCatalogDetailResponses = {
    /**
     * Successful Response
     */
    200: ApiDetail;
};

export type catalogGetCatalogDetailResponse = catalogGetCatalogDetailResponses[keyof catalogGetCatalogDetailResponses];

export type adminCatalogDeleteCatalogDefinitionData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/admin/catalog/{slug}';
};

export type adminCatalogDeleteCatalogDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCatalogDeleteCatalogDefinitionError = adminCatalogDeleteCatalogDefinitionErrors[keyof adminCatalogDeleteCatalogDefinitionErrors];

export type adminCatalogDeleteCatalogDefinitionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type adminCatalogDeleteCatalogDefinitionResponse = adminCatalogDeleteCatalogDefinitionResponses[keyof adminCatalogDeleteCatalogDefinitionResponses];

export type adminCatalogUpdateCatalogDefinitionData = {
    body: ApiDefinitionUpdate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/admin/catalog/{slug}';
};

export type adminCatalogUpdateCatalogDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCatalogUpdateCatalogDefinitionError = adminCatalogUpdateCatalogDefinitionErrors[keyof adminCatalogUpdateCatalogDefinitionErrors];

export type adminCatalogUpdateCatalogDefinitionResponses = {
    /**
     * Successful Response
     */
    200: ApiDefinitionAdmin;
};

export type adminCatalogUpdateCatalogDefinitionResponse = adminCatalogUpdateCatalogDefinitionResponses[keyof adminCatalogUpdateCatalogDefinitionResponses];

export type adminCatalogCreateCatalogDefinitionData = {
    body: ApiDefinitionCreate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/admin/catalog/{slug}';
};

export type adminCatalogCreateCatalogDefinitionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminCatalogCreateCatalogDefinitionError = adminCatalogCreateCatalogDefinitionErrors[keyof adminCatalogCreateCatalogDefinitionErrors];

export type adminCatalogCreateCatalogDefinitionResponses = {
    /**
     * Successful Response
     */
    201: ApiDefinitionAdmin;
};

export type adminCatalogCreateCatalogDefinitionResponse = adminCatalogCreateCatalogDefinitionResponses[keyof adminCatalogCreateCatalogDefinitionResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
