from __future__ import annotations

import hashlib
import json
import math
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any

from app.services.redis import RedisStore, RedisUnavailable


class InvalidCacheKey(ValueError):
    """The cache key was not produced from a fixed API slug and parameters."""


class CacheUnavailable(RuntimeError):
    """The cache store could not be read or written safely."""


_SLUG_PATTERN = re.compile(r"[a-z0-9][a-z0-9._-]{0,99}\Z")
_CACHE_KEY_PATTERN = re.compile(
    r"yeyu:cache:(?P<slug>[a-z0-9][a-z0-9._-]{0,99}):(?P<fingerprint>[0-9a-f]{64})\Z"
)


@dataclass(frozen=True, slots=True, init=False)
class CacheKey:
    """Immutable cache handle bound to one ``CacheService`` factory."""

    api_slug: str
    fingerprint: str
    _owner_token: object = field(repr=False)

    @classmethod
    def _create(
        cls,
        *,
        api_slug: str,
        fingerprint: str,
        owner_token: object,
    ) -> CacheKey:
        slug = _validate_slug(api_slug)
        value = f"yeyu:cache:{slug}:{fingerprint}"
        if _CACHE_KEY_PATTERN.fullmatch(value) is None:
            raise InvalidCacheKey("cache key fingerprint is invalid")
        key = object.__new__(cls)
        object.__setattr__(key, "api_slug", slug)
        object.__setattr__(key, "fingerprint", fingerprint)
        object.__setattr__(key, "_owner_token", owner_token)
        return key

    @property
    def value(self) -> str:
        return f"yeyu:cache:{self.api_slug}:{self.fingerprint}"

    def __str__(self) -> str:
        return self.value

    def __repr__(self) -> str:
        return f"CacheKey({self.value!r})"


def _normalize_value(value: Any) -> Any:
    if isinstance(value, Mapping):
        normalized: dict[str, Any] = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise InvalidCacheKey("cache parameter keys must be strings")
            normalized[key] = _normalize_value(item)
        return {key: normalized[key] for key in sorted(normalized)}
    if isinstance(value, (list, tuple)):
        return [_normalize_value(item) for item in value]
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    raise InvalidCacheKey("cache parameters must be JSON-serializable")


def _validate_slug(api_slug: str) -> str:
    if not isinstance(api_slug, str) or _SLUG_PATTERN.fullmatch(api_slug) is None:
        raise InvalidCacheKey("cache API slug must be a fixed lowercase slug")
    return api_slug


def normalized_parameter_fingerprint(params: Mapping[str, Any]) -> str:
    if not isinstance(params, Mapping):
        raise InvalidCacheKey("cache parameters must be a mapping")
    normalized = _normalize_value(params)
    try:
        encoded = json.dumps(
            normalized,
            ensure_ascii=False,
            allow_nan=False,
            separators=(",", ":"),
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise InvalidCacheKey("cache parameters must be JSON-serializable") from exc
    return hashlib.sha256(encoded).hexdigest()


def build_cache_key(api_slug: str, params: Mapping[str, Any]) -> str:
    """Build a canonical string for diagnostics and untrusted boundaries.

    ``CacheService`` low-level operations deliberately require a local,
    service-bound ``CacheKey`` handle instead of accepting this string.
    """

    slug = _validate_slug(api_slug)
    fingerprint = normalized_parameter_fingerprint(params)
    return f"yeyu:cache:{slug}:{fingerprint}"


def _validate_cache_key(
    cache_key: object,
    *,
    owner_token: object,
) -> CacheKey:
    if (
        not isinstance(cache_key, CacheKey)
        or type(cache_key) is not CacheKey
        or cache_key._owner_token is not owner_token
        or _CACHE_KEY_PATTERN.fullmatch(cache_key.value) is None
    ):
        raise InvalidCacheKey(
            "cache key must be generated by this cache service's factory"
        )
    return cache_key


def _utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


@dataclass(frozen=True)
class CacheMeta:
    cache_hit: bool
    stale: bool
    stale_reason: str | None
    data_at: datetime


@dataclass(frozen=True)
class CacheValue:
    payload: Any
    meta: CacheMeta

    @property
    def data(self) -> Any:
        return self.payload

    @property
    def metadata(self) -> CacheMeta:
        return self.meta


class CacheService:
    def __init__(
        self,
        client: Any | None = None,
        *,
        redis: Any | None = None,
        default_ttl_seconds: int = 60,
        max_stale_age_seconds: int = 3600,
    ) -> None:
        if client is not None and redis is not None:
            raise ValueError("provide either client or redis, not both")
        if default_ttl_seconds <= 0 or max_stale_age_seconds < 0:
            raise ValueError("cache TTL values are out of range")
        selected = redis if redis is not None else client
        self.store = selected if isinstance(selected, RedisStore) else RedisStore(selected)
        self.default_ttl_seconds = default_ttl_seconds
        self.max_stale_age_seconds = max_stale_age_seconds
        self._owner_token = object()

    def key_for(self, api_slug: str, params: Mapping[str, Any]) -> CacheKey:
        return CacheKey._create(
            api_slug=api_slug,
            fingerprint=normalized_parameter_fingerprint(params),
            owner_token=self._owner_token,
        )

    def _read_entry(
        self,
        cache_key: CacheKey,
        *,
        current: datetime,
    ) -> dict[str, Any] | None:
        _validate_cache_key(cache_key, owner_token=self._owner_token)
        try:
            raw = self.store.get(cache_key.value)
        except RedisUnavailable as exc:
            raise CacheUnavailable from exc
        if raw is None:
            return None
        if isinstance(raw, bytes):
            try:
                raw = raw.decode("utf-8")
            except UnicodeDecodeError as exc:
                raise CacheUnavailable("cache entry is not valid UTF-8") from exc
        try:
            entry = json.loads(raw)
        except (TypeError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise CacheUnavailable("cache entry is not valid JSON") from exc
        if not isinstance(entry, dict):
            raise CacheUnavailable("cache entry has an invalid shape")
        try:
            entry["data_at"] = _utc(datetime.fromisoformat(entry["data_at"]))
            entry["expires_at"] = _utc(datetime.fromisoformat(entry["expires_at"]))
            entry["stale_until"] = _utc(
                datetime.fromisoformat(entry["stale_until"])
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise CacheUnavailable("cache entry has invalid timestamps") from exc
        if "payload" not in entry:
            raise CacheUnavailable("cache entry has no payload")
        data_at = entry["data_at"]
        expires_at = entry["expires_at"]
        stale_until = entry["stale_until"]
        if data_at > current:
            raise CacheUnavailable("cache entry data timestamp is in the future")
        if data_at > expires_at or expires_at > stale_until:
            raise CacheUnavailable("cache entry timestamps are out of order")
        try:
            maximum_stale_until = expires_at + timedelta(
                seconds=self.max_stale_age_seconds
            )
        except OverflowError as exc:
            raise CacheUnavailable("cache entry timestamp exceeds safe range") from exc
        if stale_until > maximum_stale_until:
            raise CacheUnavailable("cache entry exceeds configured stale window")
        return entry

    @staticmethod
    def _value(entry: dict[str, Any], *, stale: bool, reason: str | None) -> CacheValue:
        return CacheValue(
            payload=entry["payload"],
            meta=CacheMeta(
                cache_hit=True,
                stale=stale,
                stale_reason=reason,
                data_at=entry["data_at"],
            ),
        )

    def set(
        self,
        cache_key: CacheKey,
        payload: Any,
        *,
        data_at: datetime | None = None,
        now: datetime | None = None,
        ttl_seconds: int | None = None,
        max_stale_age_seconds: int | None = None,
    ) -> None:
        _validate_cache_key(cache_key, owner_token=self._owner_token)
        ttl = self.default_ttl_seconds if ttl_seconds is None else ttl_seconds
        stale_age = (
            self.max_stale_age_seconds
            if max_stale_age_seconds is None
            else max_stale_age_seconds
        )
        if ttl <= 0 or stale_age < 0:
            raise ValueError("cache TTL values are out of range")
        current = _utc(now or datetime.now(UTC))
        observed_at = _utc(data_at or current)
        if observed_at > current:
            raise ValueError("data_at cannot be in the future")
        stale_age = min(stale_age, self.max_stale_age_seconds)
        expires_at = observed_at + timedelta(seconds=ttl)
        stale_until = expires_at + timedelta(seconds=stale_age)
        entry = {
            "payload": payload,
            "data_at": observed_at.isoformat(),
            "expires_at": expires_at.isoformat(),
            "stale_until": stale_until.isoformat(),
        }
        try:
            encoded = json.dumps(
                entry,
                ensure_ascii=False,
                allow_nan=False,
                separators=(",", ":"),
            )
        except (TypeError, ValueError) as exc:
            raise InvalidCacheKey("cache payload must be JSON-serializable") from exc
        retention = max(1, math.ceil((stale_until - current).total_seconds()))
        try:
            if not self.store.set(
                cache_key.value,
                encoded,
                ttl_seconds=retention,
            ):
                raise CacheUnavailable("cache store rejected the write")
        except RedisUnavailable as exc:
            raise CacheUnavailable from exc

    def get(
        self,
        cache_key: CacheKey,
        *,
        now: datetime | None = None,
    ) -> CacheValue | None:
        current = _utc(now or datetime.now(UTC))
        entry = self._read_entry(cache_key, current=current)
        if entry is None:
            return None
        if current < entry["expires_at"]:
            return self._value(entry, stale=False, reason=None)
        return None

    def stale_value(
        self,
        cache_key: CacheKey,
        *,
        now: datetime | None = None,
        stale_reason: str = "upstream_error",
    ) -> CacheValue | None:
        if not stale_reason or not stale_reason.strip():
            raise ValueError("stale_reason must not be empty")
        current = _utc(now or datetime.now(UTC))
        entry = self._read_entry(cache_key, current=current)
        if entry is None:
            return None
        if current < entry["expires_at"] or current >= entry["stale_until"]:
            return None
        return self._value(entry, stale=True, reason=stale_reason.strip())

    def get_for(
        self,
        api_slug: str,
        params: Mapping[str, Any],
        *,
        now: datetime | None = None,
    ) -> CacheValue | None:
        return self.get(self.key_for(api_slug, params), now=now)

    def set_for(
        self,
        api_slug: str,
        params: Mapping[str, Any],
        payload: Any,
        **kwargs: Any,
    ) -> None:
        self.set(self.key_for(api_slug, params), payload, **kwargs)

    def stale_value_for(
        self,
        api_slug: str,
        params: Mapping[str, Any],
        **kwargs: Any,
    ) -> CacheValue | None:
        return self.stale_value(self.key_for(api_slug, params), **kwargs)
