/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminApisRouteImport } from './routes/_layout/admin-apis'
import { Route as LayoutAdminAuditRouteImport } from './routes/_layout/admin-audit'
import { Route as LayoutAdminHealthRouteImport } from './routes/_layout/admin-health'
import { Route as LayoutAdminPoliciesRouteImport } from './routes/_layout/admin-policies'
import { Route as LayoutAdminTrialPoolRouteImport } from './routes/_layout/admin-trial-pool'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogSlugRouteImport } from './routes/catalog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminApisRoute = LayoutAdminApisRouteImport.update({
  id: '/admin-apis',
  path: '/admin-apis',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAuditRoute = LayoutAdminAuditRouteImport.update({
  id: '/admin-audit',
  path: '/admin-audit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminHealthRoute = LayoutAdminHealthRouteImport.update({
  id: '/admin-health',
  path: '/admin-health',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminPoliciesRoute = LayoutAdminPoliciesRouteImport.update({
  id: '/admin-policies',
  path: '/admin-policies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminTrialPoolRoute = LayoutAdminTrialPoolRouteImport.update({
  id: '/admin-trial-pool',
  path: '/admin-trial-pool',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/admin-apis': typeof LayoutAdminApisRoute
  '/admin-audit': typeof LayoutAdminAuditRoute
  '/admin-health': typeof LayoutAdminHealthRoute
  '/admin-policies': typeof LayoutAdminPoliciesRoute
  '/admin-trial-pool': typeof LayoutAdminTrialPoolRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/admin-apis': typeof LayoutAdminApisRoute
  '/admin-audit': typeof LayoutAdminAuditRoute
  '/admin-health': typeof LayoutAdminHealthRoute
  '/admin-policies': typeof LayoutAdminPoliciesRoute
  '/admin-trial-pool': typeof LayoutAdminTrialPoolRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/catalog': typeof CatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/admin-apis': typeof LayoutAdminApisRoute
  '/_layout/admin-audit': typeof LayoutAdminAuditRoute
  '/_layout/admin-health': typeof LayoutAdminHealthRoute
  '/_layout/admin-policies': typeof LayoutAdminPoliciesRoute
  '/_layout/admin-trial-pool': typeof LayoutAdminTrialPoolRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-apis'
    | '/admin-audit'
    | '/admin-health'
    | '/admin-policies'
    | '/admin-trial-pool'
    | '/dashboard'
    | '/items'
    | '/settings'
    | '/catalog/$slug'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-apis'
    | '/admin-audit'
    | '/admin-health'
    | '/admin-policies'
    | '/admin-trial-pool'
    | '/dashboard'
    | '/items'
    | '/settings'
    | '/catalog/$slug'
    | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/admin-apis'
    | '/_layout/admin-audit'
    | '/_layout/admin-health'
    | '/_layout/admin-policies'
    | '/_layout/admin-trial-pool'
    | '/_layout/dashboard'
    | '/_layout/items'
    | '/_layout/settings'
    | '/catalog/$slug'
    | '/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-apis': {
      id: '/_layout/admin-apis'
      path: '/admin-apis'
      fullPath: '/admin-apis'
      preLoaderRoute: typeof LayoutAdminApisRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-audit': {
      id: '/_layout/admin-audit'
      path: '/admin-audit'
      fullPath: '/admin-audit'
      preLoaderRoute: typeof LayoutAdminAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-health': {
      id: '/_layout/admin-health'
      path: '/admin-health'
      fullPath: '/admin-health'
      preLoaderRoute: typeof LayoutAdminHealthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-policies': {
      id: '/_layout/admin-policies'
      path: '/admin-policies'
      fullPath: '/admin-policies'
      preLoaderRoute: typeof LayoutAdminPoliciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-trial-pool': {
      id: '/_layout/admin-trial-pool'
      path: '/admin-trial-pool'
      fullPath: '/admin-trial-pool'
      preLoaderRoute: typeof LayoutAdminTrialPoolRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAdminApisRoute: typeof LayoutAdminApisRoute
  LayoutAdminAuditRoute: typeof LayoutAdminAuditRoute
  LayoutAdminHealthRoute: typeof LayoutAdminHealthRoute
  LayoutAdminPoliciesRoute: typeof LayoutAdminPoliciesRoute
  LayoutAdminTrialPoolRoute: typeof LayoutAdminTrialPoolRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAdminApisRoute: LayoutAdminApisRoute,
  LayoutAdminAuditRoute: LayoutAdminAuditRoute,
  LayoutAdminHealthRoute: LayoutAdminHealthRoute,
  LayoutAdminPoliciesRoute: LayoutAdminPoliciesRoute,
  LayoutAdminTrialPoolRoute: LayoutAdminTrialPoolRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
